### ISSUE TITLE
how to get the finetuned detections on VCL DRG and Yours

### ISSUE THREAD

**Issue by SISTMrL** [fredzzhang/spatially-conditioned-graphs#54]
hello, I can't download the finetuned detections, could you give me a link ? thanks, looking forward to your reply

**Comment by fredzzhang** [comment]
Hi, @SISTMrL 

You will be able to download the detections by running the commands below following the listed instructions
```bash
cd /path/to/spatially-conditioned-graphs/download
bash download_checkpoint.sh
```

Note that connecting to google drive could sometimes take up to one minute. So after executing the commands, if you are seeing `Connecting...`, then you are doing the right thing. Just wait patiently.

Let me know if it works.

Cheers,
Fred

**Comment by fredzzhang** [comment]
There hasn't been any responses for a few days. I assume this has been solved.
