### ISSUE TITLE
Inference code 

### ISSUE THREAD

**Issue by abhigoku10** [fredzzhang/spatially-conditioned-graphs#59]
@fredzzhang @nikanor97   hi thanks for sharing the code base great work 

1. do we inference code which we can run on the custom data / custom videos and visualize the results 
2. currently when i tested the model using test.py for some scenes present in the validation data like an only person running on a beach without any other object present there is no detections/activity in the output, is there any way i can get results like people walking , fighting, waving without depending on the object present in the scene

Thanks in advance

**Comment by fredzzhang** [comment]
Hi, @abhigoku10 

Thanks for taking interest in our work.

> do we inference code which we can run on the custom data / custom videos and visualize the results

You can try to set up your customised dataset in the same way as `HICODet` [here](https://github.com/fredzzhang/hicodet/blob/8662f9ecbf822bd5b83aae6b8206c6df167303a9/hicodet.py)

> is there any way i can get results like people walking , fighting, waving without depending on the object present in the scene

Unfortunately no. The model is designed for human-object interaction, which involves a `(human, verb, object)` triplet.

**Comment by kruthikakr** [comment]
Hi

I am trying to run the code on the image from the dataset. where can i get 
Inference script to test the image in the HICODet dataset ?

**Comment by fredzzhang** [comment]
Hi @kruthikakr 

You can find `demo.py` under the directory `diagnosis`.

**Comment by kruthikakr** [comment]
@fredzzhang  Thank you ..  i was able to run the demo.

But for the custom data , can you give some more inputs for data preparation so that  the model can be used to find the human object interaction.

**Comment by fredzzhang** [comment]
Hi @kruthikakr,

Please refer to fredzzhang/hicodet#18 and #63.

Fred.

**Comment by afzaalhussain50** [comment]
Hi @fredzzhang,
i am using demo.py for inference, but getting an error invalid 
keyError output['labels'] in visualize_entire_image() function
because you are passing output[0] of network to visualize_entire_image(dataset, output[0])
but net output does not contains ['labels']

from where i can get these labels, either these are detections labels or something other which i am missing?

Thanks

**Comment by fredzzhang** [comment]
Hi @afzaalhussain50,

The labels are computed based on the ground truth detections. See line 128 in `demo.py`,

```python
...
output = net(image, detection, target)
...
```
The target is passed to the network as well. You probably changed the code somewhere.

Fred.

**Comment by afzaalhussain50** [comment]
@fredzzhang 
I am using demo.py on custom dataset which is not labeled so i am passing target as None, which you are also mentioned in an other issue.
https://github.com/fredzzhang/spatially-conditioned-graphs/issues/63#issuecomment-917925198

`
detection = a dictionary with {'boxes', 'labels' and 'scores'} which are computed by preprocessing.py
output = net(image, detection, None)
`
and output[0] have these dictionary items where 'labels' is not present, output[0] shown in image.

![dict-keys](https://user-images.githubusercontent.com/11573574/144250558-a78336d0-3ae3-4469-86db-15ee8af1e904.JPG)

and also guide me one thing more how i can compute hoi (human action object) triplet using above network results?

Thanks for your quick response.

**Comment by fredzzhang** [comment]
Hi @afzaalhussain50,

If you are using custom dataset, just comment out the lines that referenced `labels`. That'd be line 71 and 82.

Fred.
