### ISSUE TITLE
How can i use the pretrained HICO model for OKVQA action detections

### ISSUE THREAD

**Issue by ifmaq1** [fredzzhang/spatially-conditioned-graphs#64]
Hi,
I want to retrieve the action detections on OKVQA dataset. I only want to detect actions on OKVQA dataset using pretrained HICO model. Can you please guide me how do I do that?

Also, do I need object detections on OKVQA beforehand? in order to use HICO pretrained model on it?

I read https://github.com/fredzzhang/spatially-conditioned-graphs/issues/63 too. but I didn't understand how to implement it to my problem

**Comment by fredzzhang** [comment]
Hi @ifmaq1 ,

You do need object detections to run the model. The simplest thing to do is to run Faster R-CNN pre-trained on MS COCO on your dataset. The model is available in torchvision model zoo.

To run our model on custom dataset, you just need to get the inputs correct. The model takes three inputs as shown [here](https://github.com/fredzzhang/spatially-conditioned-graphs/blob/main/models.py#L66), a list of images, a list of detections and a list of targets. If you are running inference only, leave the target as None. The detections should be a list of dictionaries as shown [here](https://github.com/fredzzhang/spatially-conditioned-graphs/blob/main/interaction_head.py#L279).

Hope that answers you questions.

Cheers,
Fred.

**Comment by ifmaq1** [comment]
Thanks alot. That was really helpful
