### ISSUE TITLE
How to use the 'CacheTemplate' class when testing for V-COCO?

### ISSUE THREAD

**Issue by Touger** [fredzzhang/spatially-conditioned-graphs#72]
Hi,

Recently, I tried to test a model on V-COCO dataset. I found that there is a class 'CacheTemplate' provided in README.md, however, I don't know how to use that correctly. 

I tried to add that class to the V-COCO eval file directly, but it doesn't work - the file keep loading the detection file over half an hour and nothing happened. Could you please give more detail for using that class? Thanks a lot！

Here is my evaluation code.
```python
from vsrl_eval import VCOCOeval
from collections import defaultdict

class CacheTemplate(defaultdict):
    """A template for VCOCO cached results """
    def __init__(self, **kwargs):
        super().__init__()
        for k, v in kwargs.items():
            self[k] = v
    def __missing__(self, k):
        seg = k.split('_')
        # Assign zero score to missing actions
        if seg[-1] == 'agent':
            return 0.
        # Assign zero score and a tiny box to missing <action,role> pairs
        else:
            return [0., 0., .1, .1, 0.]


if __name__ == "__main__":
    vsrl_annot_file = "data/vcoco/vcoco_test.json"
    coco_file = "data/instances_vcoco_all_2014.json"
    split_file = "data/splits/vcoco_test.ids"
    det_file = "../SCG/vcoco_cache/vcoco_results.pkl"
    vcocoeval = VCOCOeval(vsrl_annot_file, coco_file, split_file)
    vcocoeval._do_eval(det_file, ovr_thresh=0.5)
```

**Comment by Touger** [comment]
I waited for longer and then got the result, hhhh. The offical evaluation code is time costly. There is nothing wrong in the evaluation code.

**Comment by fredzzhang** [comment]
@Touger,

You can get around the slow evaluation by compiling with Python3. Although the official evaluation code is written in Python2, you only need to change a few lines of code.

Fred.

**Comment by Touger** [comment]
Sincerely thanks for your reply!
