### ISSUE TITLE
hi,about dataset

### ISSUE THREAD

**Issue by jun0wanan** [fredzzhang/spatially-conditioned-graphs#75]
hi,
     Thanks for your code! I want to run it ,but the dataset I find it  is difficult to download when I run bash ***.sh >?<... Can you give us a link to download?

Best,
Junlin

**Comment by fredzzhang** [comment]
Hi @jun0wanan,

You can try the websites for [HICO-DET](http://www-personal.umich.edu/~ywchao/hico/) and [MS COCO](https://cocodataset.org/#home).

Fred.
