### ISSUE TITLE
Trained Model with ResNet101 on HICO

### ISSUE THREAD

**Issue by fangruizhu** [fredzzhang/spatially-conditioned-graphs#76]
Hi, could you release the trained model of HICO with ResNet-101 as the backbone? Thanks!

**Comment by fredzzhang** [comment]
Hi @fangruizhu,

I assume you are referring to the more recent results with DETR-ResNet101. The HOI model was not changed but simply re-trained on detections produced by DETR. If you don't want to re-train the model, you can simply use the same weights but rather the test set detections produced by the corresponding [DETR](https://github.com/fredzzhang/hicodet/tree/main/detections#train-and-test-detr-on-hico-det) model.

Cheers,
Fred.

**Comment by fangruizhu** [comment]
> Hi @fangruizhu,
> 
> I assume you are referring to the more recent results with DETR-ResNet101. The HOI model was not changed but simply re-trained on detections produced by DETR. If you don't want to re-train the model, you can simply use the same weights but rather the test set detections produced by the corresponding [DETR](https://github.com/fredzzhang/hicodet/tree/main/detections#train-and-test-detr-on-hico-det) model.
> 
> Cheers, Fred.

Got it. Thanks!
