### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by wangjunbianqiang** [fredzzhang/spatially-conditioned-graphs#78]
How to fill in the --model--path parameter of the demo.py file.？When I fill in the path with the ckpt file I trained using the vcoco dataset, the error is displayed：
RuntimeError: Error(s) in loading state_dict for SpatiallyConditionedGraph:
        size mismatch for interaction_head.box_pair_predictor.weight: copying a param with shape torch.Size([24, 2048]) from checkpoint, the shape in current model is torch.Size([117, 2048]).

**Comment by wangjunbianqiang** [comment]
I see. The data set defined in your file is HICODET. I ran bash Download. sh but could not download hico. Do you know how to solve it?

**Comment by fredzzhang** [comment]
Hi @wangjunbianqiang,

The download script usually takes a while depending on your local connection. If you see `connecting...`, that means the script is working properly. It might take a minute for it to start downloading. Also, the source files are on Google drive, so make sure your internet allows you to connect to Google service.

Cheers,
Fred.

**Comment by wangjunbianqiang** [comment]
Hello ,
When I run the bash download.sh command, this error occurs，How should I fix it?
![image](https://user-images.githubusercontent.com/93476050/164977173-50598889-41cf-422f-9f32-a39afc7dcaa3.png)

**Comment by fredzzhang** [comment]
You probably don't have access to Google drive. Here is the link to the file https://drive.google.com/file/d/1QZcJmGVlF9f4h-XLWe9Gkmnmj2z1gSnk/view. You can try downloading it from the webpage.

**Comment by wangjunbianqiang** [comment]
Ok, I will try it. In addition,I want to ask can I get the results mentioned in your paper with the vcoco dataset? I saw in README.md that you wrote that you did not give the evaluation code for vcoco

**Comment by fredzzhang** [comment]
Yes we did not implement evaluation code for VCOCO, since instead use the official evaluation code provided by [Gupta et al.](https://github.com/s-gupta/v-coco#evaluation)

**Comment by wangjunbianqiang** [comment]
Excuse me, when I run 
python main.py --world-size 8 \
    --dataset vcoco --partitions trainval val --data-root vcoco \
    --train-detection-dir vcoco/detections/trainval \
    --val-detection-dir vcoco/detections/trainval \
    --print-interval 20 --cache-dir checkpoints/vcoco &>log &
this error occurs
![image](https://user-images.githubusercontent.com/93476050/165520081-6f1010e1-3afb-4207-a39c-919e3a741235.png)

 how to solve it?

**Comment by fredzzhang** [comment]
You are running the command at a directory that you don't have admin access to.

**Comment by wangjunbianqiang** [comment]
Yes, I just found out. I changed it, but another error occurred
![image](https://user-images.githubusercontent.com/93476050/165523498-d460beb5-aa08-4256-bc75-06a8070265b2.png)

**Comment by fredzzhang** [comment]
The point of redirecting `stdout` and `stderr` to the file `log` is to save the information. You need to look into the log to find out why.

**Comment by fredzzhang** [comment]
Were you able to check the log?

**Comment by wangjunbianqiang** [comment]
No, I didn't find this log file. When I remove the "&>log &", it works fine. This generated seven PT model files, after which the test produced a vcoco.pkl file, then I evaluated the Vcoco implementation based on the method you mentioned, and there was an error
![image](https://user-images.githubusercontent.com/93476050/165904824-905a4381-93b1-4660-9c23-017829e03751.png)

**Comment by wangjunbianqiang** [comment]
Here's an evaluation code I wrote based on the link you provided: eval.py
![image](https://user-images.githubusercontent.com/93476050/165905096-2b9e4395-2096-413d-a810-f165c9388518.png)
Assert indicates that
![image](https://user-images.githubusercontent.com/93476050/165905383-1c46150e-449c-456d-b6ea-41f655959144.png)

**Comment by fredzzhang** [comment]
That seems like a problem with the evaluation code. I'm not very familiar with the detailed implementations, but you could try to cache the variable `rec` and investigate.

**Comment by wangjunbianqiang** [comment]
When I was training with the HOCI data set, the following error occurred near the end of the first epoch of training
![image](https://user-images.githubusercontent.com/93476050/166226911-c520cc21-1935-489a-b2d4-855d998472e5.png)
How can I solve it?

**Comment by fredzzhang** [comment]
That's only part of the error message that shows the multiprocessing has stopped, which is not the cause of the issue. You have to post the entire error message.

**Comment by wangjunbianqiang** [comment]
I trained on one GPU

Traceback (most recent call last):
  File "main.py", line 174, in <module>
    mp.spawn(main, nprocs=args.world_size, args=(args,))
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 105, in join
    raise Exception(
Exception: process 0 terminated with signal SIGBUS

**Comment by fredzzhang** [comment]
I've never run into `Exception: process 0 terminated with signal SIGSEGV` before. So I'm not sure how to solve it. You can try to google that error.

**Comment by wangjunbianqiang** [comment]
OK.Thanks

**Comment by wangjunbianqiang** [comment]
Excuse me, could you please tell me the specific meanings of prior and label? I didn't see relevant explanation in your paper, maybe I overlooked it.
![image](https://user-images.githubusercontent.com/93476050/166675467-502051a5-c612-4080-b6a6-4e746df02ebb.png)

**Comment by fredzzhang** [comment]
`prior` refers to object detection scores for the human and object instances. `label` is self-explanatory. A positive pair will be labelled as `True`.
